seta_inclinada_esquerda_cima = '↖'
seta_cima = '↑'
seta_inclinada_direta_cima = '↗'
seta_esquerda = '←'
seta_direita = '→'
seta_baixo = '↓'
seta_inclinada_esquerda_baixo = '↙'
seta_inclinada_direta_baixo = '↘'

block = '█'
block_2 ='▒'